### ISSUE TITLE
ValueError: cfg must have tokenizer config to create a tokenizer !

### ISSUE THREAD

**Issue by answer1201** [nvidia-riva/tutorials#72]
Training or Fine-Tuning an Acoustic Model：
Model fine-tuning is a set of techniques that makes fine adjustments to a pre-existing model using new data, so as to make it adapt to new situations while also retaining its original capabilities.
so I download this model:speechtotext_zh_cn_conformer.tlt and modidy the evaluate.yaml on test_ds.labels to the Mandarin then use this api:
!tao speech_to_text_citrinet evaluate
-e $SPECS_DIR/speech_to_text_citrinet/evaluate.yaml
-g 1
-k $KEY
-m $RESULTS_DIR/speechtotext_zh_cn_conformer.tlt
-r $RESULTS_DIR/citrinet/evaluate
test_ds.manifest_filepath=$DATA_DIR/train.json
but i got this error
raise ValueError("cfg must have tokenizer config to create a tokenizer !")
ValueError: cfg must have tokenizer config to create a tokenizer !

**Comment by messiaen** [comment]
Please see the "Create Tokenizer" portion of this tutorial.

https://github.com/nvidia-riva/tutorials/blob/ac63928a0ef7937113ac8b242d598857dd267296/asr-python-advanced-finetune-am-conformer-ctc-tao-finetuning.ipynb
